version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasky
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET_EXPIRES_IN: ${NEXTAUTH_SECRET_EXPIRES_IN}
    command: sh -c "npx prisma generate && npm run start"
